Models/User.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EONRealityFinal.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }

        [StringLength(30)]
        [Required]
        public string Name { get; set; }

        [StringLength(50)]
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [BindProperty]
        public string Gender { get; set; }

        [DataType(DataType.Date)]
        [Required]
        public DateTime DateRegistered { get; set; }

        [Required]
        public string EventDays { get; set; }

        [StringLength(100)]
        public string Request { get; set; }
    }
}

Controllers/SaveController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EONRealityFinal.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace EONRealityFinal.Controllers
{
    public class SaveController : Controller
    {
        private readonly EONRealityFinal.Data.EONRealityFinalContext _context;
        public SaveController(EONRealityFinal.Data.EONRealityFinalContext context)
        {
            _context = context;
        }
        
        // GET: Save
        public ActionResult Index()
        {
            Console.WriteLine(HttpContext.Request.Form);
            User user = new User()
            {
                Name = HttpContext.Request.Form["name"],
                Email = HttpContext.Request.Form["email"],
                Gender = HttpContext.Request.Form["gender"],
                DateRegistered = Convert.ToDateTime(HttpContext.Request.Form["registeredDate"]),
                EventDays = HttpContext.Request.Form["eventDays"],
                Request = HttpContext.Request.Form["request"]
            };
            _context.Users.Add(user);
            try
            {
                _context.SaveChanges();
            }
            catch
            {
                return View();
            }
            
            return LocalRedirect("/Users");
        }

        // GET: Save/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Save/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Save/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Save/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Save/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Save/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Save/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EONRealityFinal.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EONRealityFinal.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace EONRealityFinal.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Users/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using EONRealityFinal.Data;
using EONRealityFinal.Models;

namespace EONRealityFinal.Pages.Users
{
    public class CreateModel : PageModel
    {
        private readonly EONRealityFinal.Data.EONRealityFinalContext _context;

        public CreateModel(EONRealityFinal.Data.EONRealityFinalContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public User User { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            Console.WriteLine(User);

            _context.Users.Add(User);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Users/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EONRealityFinal.Data;
using EONRealityFinal.Models;

namespace EONRealityFinal.Pages.Users
{
    public class IndexModel : PageModel
    {
        private readonly EONRealityFinal.Data.EONRealityFinalContext _context;

        public IndexModel(EONRealityFinal.Data.EONRealityFinalContext context)
        {
            _context = context;
        }

        public IList<User> User { get;set; }

        public async Task OnGetAsync()
        {
            User = await _context.Users.ToListAsync();
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
        <p>
            <a asp-page="/Users/Index">Click here to check out the Users Page</a></p>
    </div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EONRealityFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">EONRealityFinal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EONRealityFinal - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Pages/Users/Create.cshtml
@page
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<form asp-controller="Save" method="post" id="sectionForm">
    <label>Email address</label>
    <div class="form-group">
        <input type="text" class="form-control" id="name" name="name" placeholder="name" required>
    </div>

    <label>Email address</label>
    <div class="form-group">
        <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
    </div>

    <label>Gender</label></br>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="gender" id="gender1" value="Male" checked>
        <label class="form-check-label" for="gender1"> Male </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="gender" id="gender2" value="Female">
        <label class="form-check-label" for="gender2"> Female </label>
    </div>

    <label>Registered Date</label></br>
    <div class="form-group row">
        <input class="form-control" type="date" value="2019-01-01" name="registeredDate" id="example-date-input" min='2019-01-01' max='2019-06-30'>
    </div>

    <label>Selected event days</label></br>
    <div class="form-check form-check-inline events">
        <input type="checkbox" class="form-check-input" name="eventDays" value="Day 1">Day 1</br>
        <input type="checkbox" class="form-check-input" name="eventDays" value="Day 2">Day 2</br>
        <input type="checkbox" class="form-check-input" name="eventDays" value="Day 3">Day 3</br>
    </div>
    <div class="col-auto">
        <label>Request</label>
        <div class="form-group">
            <input type="text" class="form-control" id="Request" name="request" placeholder="Type additional request here" required>
        </div>
        <button type="submit" class="btn btn-primary mb-2">Submit</button>
    </div>

</form>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
<script>
    (function () {
        const form = document.querySelector('#sectionForm');
        const checkboxes = form.querySelectorAll('input[type=checkbox]');
        const checkboxLength = checkboxes.length;
        const firstCheckbox = checkboxLength > 0 ? checkboxes[0] : null;

        function init() {
            if (firstCheckbox) {
                for (let i = 0; i < checkboxLength; i++) {
                    checkboxes[i].addEventListener('change', checkValidity);
                }

                checkValidity();
            }
        }

        function isChecked() {
            for (let i = 0; i < checkboxLength; i++) {
                if (checkboxes[i].checked) return true;
            }

            return false;
        }

        function checkValidity() {
            const errorMessage = !isChecked() ? 'At least one checkbox must be selected.' : '';
            firstCheckbox.setCustomValidity(errorMessage);
        }

        init();
    })();
</script>

Pages/Users/Index.cshtml
@page
@model EONRealityFinal.Pages.Users.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].DateRegistered)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].EventDays)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User[0].Request)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.User) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateRegistered)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EventDays)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Request)
            </td>
        </tr>
}
    </tbody>
</table>